version: '3.7'

volumes:
    cartodb-redis-data:
    cartodb-postgis-data:
    cartodb-postgis-extensions:
    cartodb-uploads:
    bundle_path:
    node_modules:
services:
  cartodb-postgis:
    container_name: cartodb-postgis
    build:
      context: postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - cartodb-postgis-data:/var/lib/postgresql/data
      - cartodb-postgis-extensions:/usr/share/postgresql

  cartodb-redis:
    container_name: cartodb-redis
    build:
      context: redis
    ports:
      - 6379:6379
    volumes:
      - cartodb-redis-data:/data


  cartodb-sqlapi:
    depends_on:
      - cartodb-postgis
      - cartodb-redis
    container_name: cartodb-sqlapi
    build:
      context: sqlapi
    ports:
      - 8080:8080
    # volumes:
    #   - /workspaces/CartoDB-SQL-API:/CartoDB-SQL-API

  cartodb-mapsapi:
    depends_on:
      - cartodb-postgis
      - cartodb-redis
    container_name: cartodb-mapsapi
    build:
      context: mapsapi
    ports:
      - 8181:8181
    # volumes:
    #   - /workspaces/Windshaft-cartodb:/Windshaft-cartodb

  cartodb-editor:
    depends_on:
      - cartodb-postgis
      - cartodb-redis
      - cartodb-mapsapi
      - cartodb-sqlapi
    container_name: cartodb-editor
    command: ./docker-entrypoint.sh
    environment:
      - BUNDLE_PATH=/bundle/vendor
    build:
      context: editor
    volumes:
      # - /workspaces/cartodb:/cartodb
      - bundle_path:/bundle
      - node_modules:/cartodb/node_modules
      - ./editor/docker-entrypoint.sh:/cartodb/docker-entrypoint.sh
      - ./editor/config/base.app_config.yml:/cartodb/config/app_config.yml
      - ./editor/config/base.database.yml:/cartodb/config/database.yml
    ports:
      - 3000:3000

  cartodb-router:
    depends_on:
      - cartodb-mapsapi
      - cartodb-sqlapi
      - cartodb-editor
    container_name: cartodb-router
    build:
      context: router
    volumes:
        - cartodb-uploads:/var/www/uploads    
    ports:
      - 80:80
